### ISSUE TITLE
[vosk_sr_ros.py] Pfad fuer Sprachmodell Pfad ist nicht relativ

### ISSUE THREAD

**Issue by C-Sahin** [C-Sahin/Sprachsteuerung-Turtlesim#1]
der Pfad os.chdir("/home/sahin/catkin_ws/src/vosk_ros/src") ist auf meine Umgebung abgestimmt und nicht relativ

**Comment by Faruk64** [comment]
In welcher Datei ist das?
Und dann bitte angeben wie der Pfad umzuändern ist damit man das installieren kann. Evtll in Startanweisungen?

Vielleicht doch relative Pfade möglich mit Platzhaltern?

**Comment by C-Sahin** [comment]
fix @ https://github.com/C-Sahin/Sprachsteuerung-Turtlesim/commit/ef844b0c2a20d21a536bd5ec62d1c4a7009a2c24
